# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(400, 300)
        WelcomeWindow.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.verticalLayoutWidget = QtWidgets.QWidget(WelcomeWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 120, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_login = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_login.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button_login.setObjectName("button_login")
        self.verticalLayout.addWidget(self.button_login)
        self.button_signup = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_signup.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button_signup.setObjectName("button_signup")
        self.verticalLayout.addWidget(self.button_signup)
        self.label = QtWidgets.QLabel(WelcomeWindow)
        self.label.setGeometry(QtCore.QRect(120, 80, 171, 20))
        self.label.setObjectName("label")

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "Главное окно"))
        self.button_login.setText(_translate("WelcomeWindow", "Авторизация "))
        self.button_signup.setText(_translate("WelcomeWindow", "Регистрация "))
        self.label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Добро Пожаловать </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeWindow = QtWidgets.QWidget()
    ui = Ui_WelcomeWindow()
    ui.setupUi(WelcomeWindow)
    WelcomeWindow.show()
    sys.exit(app.exec_())
