# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bl.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BLWindow(object):
    def setupUi(self, BLWindow):
        BLWindow.setObjectName("BLWindow")
        BLWindow.resize(500, 340)
        BLWindow.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(BLWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 130, 160, 83))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button7 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.button7.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button7.setObjectName("button7")
        self.verticalLayout_2.addWidget(self.button7)
        self.button8 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.button8.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button8.setObjectName("button8")
        self.verticalLayout_2.addWidget(self.button8)
        self.button9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.button9.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button9.setObjectName("button9")
        self.verticalLayout_2.addWidget(self.button9)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(BLWindow)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(330, 40, 160, 83))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button4 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button4.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button4.setObjectName("button4")
        self.verticalLayout_3.addWidget(self.button4)
        self.button5 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button5.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button5.setObjectName("button5")
        self.verticalLayout_3.addWidget(self.button5)
        self.button6 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button6.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button6.setObjectName("button6")
        self.verticalLayout_3.addWidget(self.button6)
        self.verticalLayoutWidget = QtWidgets.QWidget(BLWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 160, 83))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button1.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button1.setObjectName("button1")
        self.verticalLayout.addWidget(self.button1)
        self.button2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button2.setObjectName("button2")
        self.verticalLayout.addWidget(self.button2)
        self.button3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button3.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button3.setObjectName("button3")
        self.verticalLayout.addWidget(self.button3)
        self.button10 = QtWidgets.QPushButton(BLWindow)
        self.button10.setGeometry(QtCore.QRect(150, 260, 201, 23))
        self.button10.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button10.setObjectName("button10")

        self.retranslateUi(BLWindow)
        QtCore.QMetaObject.connectSlotsByName(BLWindow)

    def retranslateUi(self, BLWindow):
        _translate = QtCore.QCoreApplication.translate
        BLWindow.setWindowTitle(_translate("BLWindow", "Бундеслига"))
        self.button7.setText(_translate("BLWindow", "Бохум"))
        self.button8.setText(_translate("BLWindow", "Унион(Берлин)"))
        self.button9.setText(_translate("BLWindow", "Вольфсбург"))
        self.button4.setText(_translate("BLWindow", "Фрайбург"))
        self.button5.setText(_translate("BLWindow", "Байер"))
        self.button6.setText(_translate("BLWindow", "Кёльн"))
        self.button1.setText(_translate("BLWindow", "Борусия (Дортмунд)"))
        self.button2.setText(_translate("BLWindow", "Бавария"))
        self.button3.setText(_translate("BLWindow", "РБ Лейпциг"))
        self.button10.setText(_translate("BLWindow", "Записать исход матча"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BLWindow = QtWidgets.QWidget()
    ui = Ui_BLWindow()
    ui.setupUi(BLWindow)
    BLWindow.show()
    sys.exit(app.exec_())
