# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 300)
        LoginWindow.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.input_username = QtWidgets.QLineEdit(LoginWindow)
        self.input_username.setGeometry(QtCore.QRect(60, 70, 251, 20))
        self.input_username.setObjectName("input_username")
        self.input_password = QtWidgets.QLineEdit(LoginWindow)
        self.input_password.setGeometry(QtCore.QRect(60, 130, 251, 20))
        self.input_password.setObjectName("input_password")
        self.label_username = QtWidgets.QLabel(LoginWindow)
        self.label_username.setGeometry(QtCore.QRect(60, 50, 47, 13))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(LoginWindow)
        self.label_password.setGeometry(QtCore.QRect(60, 110, 47, 13))
        self.label_password.setObjectName("label_password")
        self.button_login = QtWidgets.QPushButton(LoginWindow)
        self.button_login.setGeometry(QtCore.QRect(60, 200, 75, 23))
        self.button_login.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button_login.setObjectName("button_login")
        self.button_back = QtWidgets.QPushButton(LoginWindow)
        self.button_back.setGeometry(QtCore.QRect(240, 200, 75, 23))
        self.button_back.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button_back.setObjectName("button_back")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Вход в аккаунт"))
        self.label_username.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Логин</span></p></body></html>"))
        self.label_password.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Пароль</span></p></body></html>"))
        self.button_login.setText(_translate("LoginWindow", "Войти"))
        self.button_back.setText(_translate("LoginWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QWidget()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
