# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(400, 300)
        RegistrationWindow.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.label_username = QtWidgets.QLabel(RegistrationWindow)
        self.label_username.setGeometry(QtCore.QRect(60, 50, 47, 13))
        self.label_username.setObjectName("label_username")
        self.button_back = QtWidgets.QPushButton(RegistrationWindow)
        self.button_back.setGeometry(QtCore.QRect(240, 200, 75, 23))
        self.button_back.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button_back.setObjectName("button_back")
        self.input_username = QtWidgets.QLineEdit(RegistrationWindow)
        self.input_username.setGeometry(QtCore.QRect(60, 70, 251, 20))
        self.input_username.setObjectName("input_username")
        self.label_password = QtWidgets.QLabel(RegistrationWindow)
        self.label_password.setGeometry(QtCore.QRect(60, 110, 47, 13))
        self.label_password.setObjectName("label_password")
        self.input_password = QtWidgets.QLineEdit(RegistrationWindow)
        self.input_password.setGeometry(QtCore.QRect(60, 130, 251, 20))
        self.input_password.setObjectName("input_password")
        self.button_signup = QtWidgets.QPushButton(RegistrationWindow)
        self.button_signup.setGeometry(QtCore.QRect(60, 200, 111, 23))
        self.button_signup.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button_signup.setObjectName("button_signup")

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Регистрация"))
        self.label_username.setText(_translate("RegistrationWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Логин</span></p></body></html>"))
        self.button_back.setText(_translate("RegistrationWindow", "Назад"))
        self.label_password.setText(_translate("RegistrationWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Пароль</span></p></body></html>"))
        self.button_signup.setText(_translate("RegistrationWindow", "Зарегистрироваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationWindow = QtWidgets.QWidget()
    ui = Ui_RegistrationWindow()
    ui.setupUi(RegistrationWindow)
    RegistrationWindow.show()
    sys.exit(app.exec_())
