# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save(4).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveWindow4(object):
    def setupUi(self, SaveWindow4):
        SaveWindow4.setObjectName("SaveWindow4")
        SaveWindow4.resize(177, 219)
        SaveWindow4.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.label_team1 = QtWidgets.QLabel(SaveWindow4)
        self.label_team1.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label_team1.setObjectName("label_team1")
        self.input_result = QtWidgets.QLineEdit(SaveWindow4)
        self.input_result.setGeometry(QtCore.QRect(20, 140, 141, 20))
        self.input_result.setObjectName("input_result")
        self.label_team2 = QtWidgets.QLabel(SaveWindow4)
        self.label_team2.setGeometry(QtCore.QRect(20, 70, 141, 16))
        self.label_team2.setObjectName("label_team2")
        self.input_team2 = QtWidgets.QComboBox(SaveWindow4)
        self.input_team2.setGeometry(QtCore.QRect(20, 90, 141, 22))
        self.input_team2.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.input_team2.setObjectName("input_team2")
        self.button_save = QtWidgets.QPushButton(SaveWindow4)
        self.button_save.setGeometry(QtCore.QRect(20, 170, 141, 23))
        self.button_save.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.button_save.setObjectName("button_save")
        self.input_team1 = QtWidgets.QComboBox(SaveWindow4)
        self.input_team1.setGeometry(QtCore.QRect(20, 40, 141, 22))
        self.input_team1.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.input_team1.setObjectName("input_team1")
        self.label_result = QtWidgets.QLabel(SaveWindow4)
        self.label_result.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_result.setObjectName("label_result")

        self.retranslateUi(SaveWindow4)
        QtCore.QMetaObject.connectSlotsByName(SaveWindow4)

    def retranslateUi(self, SaveWindow4):
        _translate = QtCore.QCoreApplication.translate
        SaveWindow4.setWindowTitle(_translate("SaveWindow4", "Сохранение исхода матча"))
        self.label_team1.setText(_translate("SaveWindow4", "<html><head/><body><p><span style=\" color:#ffffff;\">Команда 1</span></p></body></html>"))
        self.label_team2.setText(_translate("SaveWindow4", "<html><head/><body><p><span style=\" color:#ffffff;\">Команда 2</span></p></body></html>"))
        self.button_save.setText(_translate("SaveWindow4", "Сохранить"))
        self.label_result.setText(_translate("SaveWindow4", "<html><head/><body><p><span style=\" color:#ffffff;\">Результат</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveWindow4 = QtWidgets.QWidget()
    ui = Ui_SaveWindow4()
    ui.setupUi(SaveWindow4)
    SaveWindow4.show()
    sys.exit(app.exec_())
