# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save(2).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveWindow2(object):
    def setupUi(self, SaveWindow2):
        SaveWindow2.setObjectName("SaveWindow2")
        SaveWindow2.resize(177, 219)
        SaveWindow2.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.input_team2 = QtWidgets.QComboBox(SaveWindow2)
        self.input_team2.setGeometry(QtCore.QRect(20, 80, 141, 22))
        self.input_team2.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.input_team2.setObjectName("input_team2")
        self.button_save = QtWidgets.QPushButton(SaveWindow2)
        self.button_save.setGeometry(QtCore.QRect(20, 160, 141, 23))
        self.button_save.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.button_save.setObjectName("button_save")
        self.input_result = QtWidgets.QLineEdit(SaveWindow2)
        self.input_result.setGeometry(QtCore.QRect(20, 130, 141, 20))
        self.input_result.setObjectName("input_result")
        self.label_result = QtWidgets.QLabel(SaveWindow2)
        self.label_result.setGeometry(QtCore.QRect(20, 110, 141, 16))
        self.label_result.setObjectName("label_result")
        self.label_team1 = QtWidgets.QLabel(SaveWindow2)
        self.label_team1.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_team1.setObjectName("label_team1")
        self.input_team1 = QtWidgets.QComboBox(SaveWindow2)
        self.input_team1.setGeometry(QtCore.QRect(20, 30, 141, 22))
        self.input_team1.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.input_team1.setObjectName("input_team1")
        self.label_team2 = QtWidgets.QLabel(SaveWindow2)
        self.label_team2.setGeometry(QtCore.QRect(20, 60, 141, 16))
        self.label_team2.setObjectName("label_team2")

        self.retranslateUi(SaveWindow2)
        QtCore.QMetaObject.connectSlotsByName(SaveWindow2)

    def retranslateUi(self, SaveWindow2):
        _translate = QtCore.QCoreApplication.translate
        SaveWindow2.setWindowTitle(_translate("SaveWindow2", "Сохранение исхода матча"))
        self.button_save.setText(_translate("SaveWindow2", "Сохранить"))
        self.label_result.setText(_translate("SaveWindow2", "<html><head/><body><p><span style=\" color:#ffffff;\">Результат</span></p></body></html>"))
        self.label_team1.setText(_translate("SaveWindow2", "<html><head/><body><p><span style=\" color:#ffffff;\">Команда 1</span></p></body></html>"))
        self.label_team2.setText(_translate("SaveWindow2", "<html><head/><body><p><span style=\" color:#ffffff;\">Команда 2</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveWindow2 = QtWidgets.QWidget()
    ui = Ui_SaveWindow2()
    ui.setupUi(SaveWindow2)
    SaveWindow2.show()
    sys.exit(app.exec_())
