# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save(1).ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveWindow(object):
    def setupUi(self, SaveWindow):
        SaveWindow.setObjectName("SaveWindow")
        SaveWindow.resize(177, 219)
        SaveWindow.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.label_team2 = QtWidgets.QLabel(SaveWindow)
        self.label_team2.setGeometry(QtCore.QRect(20, 60, 141, 16))
        self.label_team2.setObjectName("label_team2")
        self.input_result = QtWidgets.QLineEdit(SaveWindow)
        self.input_result.setGeometry(QtCore.QRect(20, 130, 141, 20))
        self.input_result.setObjectName("input_result")
        self.input_team2 = QtWidgets.QComboBox(SaveWindow)
        self.input_team2.setGeometry(QtCore.QRect(20, 80, 141, 22))
        self.input_team2.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.input_team2.setObjectName("input_team2")
        self.input_team1 = QtWidgets.QComboBox(SaveWindow)
        self.input_team1.setGeometry(QtCore.QRect(20, 30, 141, 22))
        self.input_team1.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.input_team1.setObjectName("input_team1")
        self.button_save = QtWidgets.QPushButton(SaveWindow)
        self.button_save.setGeometry(QtCore.QRect(20, 160, 141, 23))
        self.button_save.setStyleSheet("background-color: rgb(55, 255, 0);")
        self.button_save.setObjectName("button_save")
        self.label_team1 = QtWidgets.QLabel(SaveWindow)
        self.label_team1.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.label_team1.setObjectName("label_team1")
        self.label_result = QtWidgets.QLabel(SaveWindow)
        self.label_result.setGeometry(QtCore.QRect(20, 110, 141, 16))
        self.label_result.setObjectName("label_result")

        self.retranslateUi(SaveWindow)
        QtCore.QMetaObject.connectSlotsByName(SaveWindow)

    def retranslateUi(self, SaveWindow):
        _translate = QtCore.QCoreApplication.translate
        SaveWindow.setWindowTitle(_translate("SaveWindow", "Сохранение исхода матча"))
        self.label_team2.setText(_translate("SaveWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Команда 2</span></p></body></html>"))
        self.button_save.setText(_translate("SaveWindow", "Сохранить"))
        self.label_team1.setText(_translate("SaveWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Команда 1</span></p></body></html>"))
        self.label_result.setText(_translate("SaveWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Результат</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveWindow = QtWidgets.QWidget()
    ui = Ui_SaveWindow()
    ui.setupUi(SaveWindow)
    SaveWindow.show()
    sys.exit(app.exec_())
