# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectionleague.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(500, 340)
        MainPage.setStyleSheet("background-color: rgb(1, 66, 106);")
        self.layoutWidget = QtWidgets.QWidget(MainPage)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 60, 271, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button1 = QtWidgets.QPushButton(self.layoutWidget)
        self.button1.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button1.setObjectName("button1")
        self.gridLayout.addWidget(self.button1, 1, 0, 1, 1)
        self.button2 = QtWidgets.QPushButton(self.layoutWidget)
        self.button2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button2.setObjectName("button2")
        self.gridLayout.addWidget(self.button2, 1, 1, 1, 1)
        self.new_button = QtWidgets.QPushButton(self.layoutWidget)
        self.new_button.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.new_button.setObjectName("new_button")
        self.gridLayout.addWidget(self.new_button, 2, 0, 1, 2)
        self.button4 = QtWidgets.QPushButton(self.layoutWidget)
        self.button4.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button4.setObjectName("button4")
        self.gridLayout.addWidget(self.button4, 3, 1, 1, 1)
        self.button3 = QtWidgets.QPushButton(self.layoutWidget)
        self.button3.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.button3.setObjectName("button3")
        self.gridLayout.addWidget(self.button3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Выбор Лиги"))
        self.button1.setText(_translate("MainPage", "РПЛ"))
        self.button2.setText(_translate("MainPage", "АПЛ"))
        self.new_button.setText(_translate("MainPage", "Все исходы матчей"))
        self.button4.setText(_translate("MainPage", "БЛ"))
        self.button3.setText(_translate("MainPage", "ЛЧ"))
        self.label.setText(_translate("MainPage", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Выберите Лигу</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPage = QtWidgets.QWidget()
    ui = Ui_MainPage()
    ui.setupUi(MainPage)
    MainPage.show()
    sys.exit(app.exec_())
